---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2-vbox
    driver:
      box: bento/centos-7.2
      box_url: bento/centos-7.2
      provider: virtualbox
  - name: centos-7.2-vmware
    driver:
      box: bento/centos-7.2
      box_url: bento/centos-7.2
      provider: vmware_fusion
  - name: centos-7.1-vbox
    driver:
      box: bento/centos-7.1
      box_url: bento/centos-7.1
      provider: virtualbox
  - name: centos-7.1-vmware
    driver:
      box: bento/centos-7.1
      box_url: bento/centos-7.1
      provider: vmware_fusion
  - name: centos-6.8-vbox
    driver:
      box: bento/centos-6.8
      box_url: bento/centos-6.8
      provider: virtualbox
  - name: centos-6.8-vmware
    driver:
      box: bento/centos-6.8
      box_url: bento/centos-6.8
      provider: vmware_fusion
  - name: centos-6.7-vbox
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: virtualbox
  - name: centos-6.7-vmware
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: vmware_fusion
  - name:  ubuntu-trusty-vbox
    driver:
      box: ubuntu/trusty64
      box_url: ubuntu/trusty64
      provider: virtualbox

# I could not find an "official" vmware_fusion trusty box

# Adding auditd with cis ruleset addresses CIS CentOS Benchmark V1.0.0 4.2.2 and 4.2.4-18
# NOTE: 4.2.17 needs to be uncommented. and 4.2.12 needs to be confirmed. See cis template for more info.
# Note: There is probably a better way to pull in auditd and apply the cis attribute, this works for now.
suites:
  - name: default
    run_list:
      - recipe[auditd]
      - recipe[stig]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
    attributes: {
      "auditd" : {
        "ruleset" : "stig"
      }
    }
  - name: noauditd
    run_list:
      - recipe[stig::default]
